package main

import (
	"encoding/json"
	"fmt"
)

func main() {
	p1 := person{
		First: "James",
		Last:  "Bond",
		Age:   32,
	}

	p2 := person{
		First: "Miss",
		Last:  "Moneypenny",
		Age:   27,
	}
	people := []person{p1, p2}

	fmt.Println(people)

	bs, err := json.Marshal(people)
	if err != nil {
		fmt.Println(err)
	}

	fmt.Println(string(bs))

	s := `[{"First":"James","Last":"Bond","Age":32},{"First":"Miss","Last":"Moneypenny","Age":27}]`
	bs2 := []byte(s)
	fmt.Printf("%T\n", s)
	fmt.Printf("%T\n", bs2)

	// people := []person{}
	var people2 []person
	err = json.Unmarshal(bs, &people2)
	fmt.Println(people2)
	for _, v := range people2 {
		fmt.Println(v.First, v.Last, v.Age)
	}
}

type person struct {
	First string `json:"First"`
	Last  string `json:"Last"`
	Age   int    `json:"Age"`
}

// type AutoGenerated []struct {
// 	First string `json:"First"`
// 	Last  string `json:"Last"`
// 	Age   int    `json:"Age"`
// }
